name: Build and Test Next.js App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    name: Build and Test Next.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest' 
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Restore cache for faster builds
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs

      - name: Build Next.js app
        run: pnpm build

      # Upload the standalone build artifacts
      - name: Upload standalone build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.next/standalone/'  # Upload only the .next/standalone directory

      # Save cache for the next build
      - name: Save build cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package.json') }}
